datasets:

  - id: CCN20240304
    title: "Dissection: Middle temporal gyrus (MTG)"
    description: "Cellular and molecular characterization of human cortical cytoarchitecture. Dissection: Middle temporal gyrus (MTG)."
    matrix_file_id: CellXGene_dataset:015c230d-650c-4527-870d-8a805849a382
    github_org: hkir-dev
    repo: human-neocortex-middle-temporal-gyrus
    author: https://orcid.org/0000-0003-3373-7386
    accession_id_prefix: AITXXX
    labelsets:
      - CrossArea_cluster
      - CrossArea_subclass
      - Class
